version: "3"

services:
  postgres:
    image: "postgres:13"
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DATABASE: "postgres"
      POSTGRES_DB: "platform_api"
    ports:
      - "5432:5432"
